---
- name: APT
  shell: sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
- name: APT update
  shell: sudo apt update
- name: Add APT key
  apt_key:
   id: "0C49F3730359A14518585931BC711F9BA15703C6"
   keyserver: keyserver.ubuntu.com
  tags: install
- name: Add APT repository
  apt_repository:
   repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
   state: present
  tags: install
- name: Install mongodb package
  apt:
   name: mongodb-org
   state: present
  tags: install
- name: Configure service supervisor
  systemd:
   name: mongod
   enabled: yes
   state: started
  tags: install

