---
- name: Ryby and Bundler
  hosts: all
  become: true
  vars:
    app_list:
      - - ruby-full
        - ruby-bundler
        - build-essential
  tasks:
  - name: Install cycle apt
    apt: "name={{ item }} state=present"
    with_items:
      - "{{ app_list }}"
