- name: Deploy App
  vars_files:
   - group_app_hosts.yml
  hosts: "{{ group_app_hosts }}"
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/Otus-DevOps-2017-11/reddit.git'
        dest: /home/Maksim/reddit
        version: monolith
      notify: restart puma
    - name: bundle install
      bundler:
        state: present
        chdir: /home/Maksim/reddit
  handlers:
   - name: restart puma
     become: true
     systemd: name=puma state=restarted
